// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYZl3NNUQBvWblGyKxnBDgw4dnPyxOdf0',
    appId: '1:230727531481:android:a471dc7850799af4d7b7c8',
    messagingSenderId: '230727531481',
    projectId: 'new-course-e11fb',
    storageBucket: 'new-course-e11fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9O_W_rMcNHfeIta6wgezoEU240_9nb1U',
    appId: '1:230727531481:ios:44c498e213d80f7ed7b7c8',
    messagingSenderId: '230727531481',
    projectId: 'new-course-e11fb',
    storageBucket: 'new-course-e11fb.firebasestorage.app',
    iosBundleId: 'com.example.newCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfTxXczcNjQ8R-fxWQNJIpzEw_JEz49RE',
    appId: '1:230727531481:web:00e16fba480f414cd7b7c8',
    messagingSenderId: '230727531481',
    projectId: 'new-course-e11fb',
    authDomain: 'new-course-e11fb.firebaseapp.com',
    storageBucket: 'new-course-e11fb.firebasestorage.app',
  );
}
